[build.environment]
HUGO_VERSION = "0.163.3"
NODE_VERSION = "24.16.0"
TZ = "Europe/Rome"

[build]
publish = "public"
command = "npm install && hugo build --gc --minify --baseURL ${URL}"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Protegge l'area privata da indicizzazione
[[headers]]
  for = "/private/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store, no-cache, must-revalidate"
